
import React, { useState, useEffect } from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Bot, Camera, Video, Brain, BarChart3, Sparkles, Zap, Target } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";
import EnhancedCamera from './EnhancedCamera';
import { MetricsProvider } from '@/context/MetricsContext';

const InterviewCoachNew: React.FC = () => {
  const [activeTab, setActiveTab] = useState("practice-mode");
  const navigate = useNavigate();

  // Remove visibility change handler that might interfere with navigation
  useEffect(() => {
    console.log('InterviewCoachNew component mounted');
    
    return () => {
      console.log('InterviewCoachNew component unmounting');
    };
  }, []);

  // Simplified navigation handler
  const handleAIInterviewClick = () => {
    console.log('Navigating to AI Interview Coach from InterviewCoachNew...');
    navigate('/ai-interview-coach');
  };

  return (
    <MetricsProvider>
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50/30 to-indigo-50/20">
        {/* Enhanced Header Section */}
        <div className="relative overflow-hidden bg-gradient-to-r from-blue-600 via-purple-600 to-indigo-700 mb-8">
          <div className="absolute inset-0 bg-black/10"></div>
          <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent"></div>
          
          <div className="relative container mx-auto px-6 py-16">
            <div className="text-center max-w-4xl mx-auto">
              <div className="flex justify-center mb-8">
                <div className="relative">
                  <div className="absolute inset-0 bg-white/20 rounded-full blur-3xl scale-150"></div>
                  <div className="relative bg-white/10 backdrop-blur-sm rounded-full p-8 border border-white/20 shadow-2xl">
                    <Brain className="h-16 w-16 text-white" />
                  </div>
                </div>
              </div>
              
              <h1 className="text-5xl md:text-6xl font-bold text-white mb-6 leading-tight">
                Advanced Interview Coach
              </h1>
              
              <p className="text-xl text-blue-100 max-w-3xl mx-auto leading-relaxed mb-8">
                Master your interview skills with AI-powered simulation, real-time performance tracking, 
                and comprehensive analytics including posture detection, eye contact monitoring, and speech analysis.
              </p>

              {/* CTA Button */}
              <div className="flex justify-center">
                <Button 
                  size="lg"
                  onClick={handleAIInterviewClick}
                  className="bg-white/20 backdrop-blur-sm text-white border border-white/30 hover:bg-white/30 hover:shadow-2xl transform hover:scale-105 transition-all duration-300 px-8 py-4 text-lg font-semibold"
                >
                  <Sparkles className="mr-2 h-5 w-5" />
                  Start AI Interview Experience
                </Button>
              </div>
            </div>
          </div>
        </div>

        <div className="container mx-auto px-6">
          {/* Feature Cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-12">
            <Card className="bg-gradient-to-br from-blue-50 to-blue-100/50 border-blue-200/50 hover:shadow-xl transition-all duration-300 transform hover:scale-105 backdrop-blur-sm">
              <CardHeader className="pb-4">
                <div className="flex items-center justify-between mb-2">
                  <div className="bg-blue-500/10 p-3 rounded-xl">
                    <Brain className="h-8 w-8 text-blue-600" />
                  </div>
                  <div className="bg-gradient-to-r from-blue-500 to-purple-500 text-white px-3 py-1 rounded-full text-xs font-semibold">
                    AI-POWERED
                  </div>
                </div>
                <CardTitle className="text-blue-800 text-xl">
                  AI Interview Simulation
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-blue-700 mb-6 leading-relaxed">
                  Get personalized interview questions generated by advanced AI based on your job role and experience level.
                </p>
                <Button 
                  className="w-full bg-gradient-to-r from-blue-500 to-blue-600 hover:from-blue-600 hover:to-blue-700 text-white shadow-lg hover:shadow-xl transition-all duration-300" 
                  onClick={handleAIInterviewClick}
                >
                  <Zap className="mr-2 h-4 w-4" />
                  Start AI Interview
                </Button>
              </CardContent>
            </Card>

            <Card className="bg-gradient-to-br from-green-50 to-emerald-100/50 border-green-200/50 hover:shadow-xl transition-all duration-300 transform hover:scale-105 backdrop-blur-sm">
              <CardHeader className="pb-4">
                <div className="flex items-center justify-between mb-2">
                  <div className="bg-green-500/10 p-3 rounded-xl">
                    <Video className="h-8 w-8 text-green-600" />
                  </div>
                  <div className="bg-gradient-to-r from-green-500 to-emerald-500 text-white px-3 py-1 rounded-full text-xs font-semibold">
                    REAL-TIME
                  </div>
                </div>
                <CardTitle className="text-green-800 text-xl">
                  Live Performance Tracking
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-green-700 leading-relaxed">
                  Monitor your posture, eye contact, hand gestures, and speech patterns in real-time during the interview.
                </p>
              </CardContent>
            </Card>

            <Card className="bg-gradient-to-br from-purple-50 to-violet-100/50 border-purple-200/50 hover:shadow-xl transition-all duration-300 transform hover:scale-105 backdrop-blur-sm">
              <CardHeader className="pb-4">
                <div className="flex items-center justify-between mb-2">
                  <div className="bg-purple-500/10 p-3 rounded-xl">
                    <BarChart3 className="h-8 w-8 text-purple-600" />
                  </div>
                  <div className="bg-gradient-to-r from-purple-500 to-violet-500 text-white px-3 py-1 rounded-full text-xs font-semibold">
                    ANALYTICS
                  </div>
                </div>
                <CardTitle className="text-purple-800 text-xl">
                  Smart Analytics
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-purple-700 leading-relaxed">
                  Receive detailed feedback on your performance with actionable insights to improve your interview skills.
                </p>
              </CardContent>
            </Card>
          </div>

          {/* Practice Mode Section */}
          <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
            <TabsList className="grid w-full grid-cols-1 mb-8 bg-white/50 backdrop-blur-sm border border-white/20">
              <TabsTrigger 
                value="practice-mode" 
                className="flex items-center gap-2 data-[state=active]:bg-white data-[state=active]:shadow-lg data-[state=active]:text-blue-700"
              >
                <Camera className="h-5 w-5" />
                Practice Mode - Camera Training
              </TabsTrigger>
            </TabsList>

            <TabsContent value="practice-mode" className="space-y-6">
              <Card className="bg-white/70 backdrop-blur-sm border border-white/20 shadow-xl">
                <CardHeader>
                  <div className="flex items-center gap-3 mb-2">
                    <div className="bg-blue-500/10 p-2 rounded-lg">
                      <Camera className="h-6 w-6 text-blue-600" />
                    </div>
                    <div>
                      <CardTitle className="text-blue-900 text-2xl">
                        Practice Mode - Camera & Posture Monitoring
                      </CardTitle>
                      <CardDescription className="text-slate-600 text-lg mt-1">
                        Practice your presentation skills with real-time feedback on posture, eye contact, and body language.
                      </CardDescription>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="p-6">
                  <div className="bg-gradient-to-br from-slate-50 to-blue-50/30 rounded-xl p-4 border border-slate-200">
                    <EnhancedCamera isInterviewActive={false} />
                  </div>
                </CardContent>
              </Card>
            </TabsContent>
          </Tabs>
        </div>
      </div>
    </MetricsProvider>
  );
};

export default InterviewCoachNew;
