// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihtqcwysnusiiacmiubw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlodHFjd3lzbnVzaWlhY21pdWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NTEyMzAsImV4cCI6MjA2MzEyNzIzMH0.2ceA_H9oL8xttcBrQR4xn1WyH96LtARQf0rmqkdbwvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);